// PROJECT ACTIONS
export const SET_PROJECT_INFO = "SET_PROJECT_INFO";
export const SET_RISK_OPTIONS = "SET_RISK_OPTIONS";
export const SET_SELECTED = "SET_SELECTED";
export const TOGGLE_RISK_DISPLAY = "TOGGLE_RISK_DISPLAY";
export const TOGGLE_PROJECT_BOOLEAN = "TOGGLE_PROJECT_BOOLEAN";
export const SET_PROJECT_ADMIN = "SET_PROJECT_ADMIN";


// RISK ACTIONS
export const UPDATE_CONSEQUENCE = "UPDATE_CONSEQUENCE";
export const UPDATE_PROBABILITY = "UPDATE_PROBABILITY";
export const UPDATE_RISK = "UPDATE_RISK";
export const DELETE_RISK = "DELETE_RISK";
export const ADD_TO_PROJECT = "ADD_TO_PROJECT";
export const SORT_BY_RISK = "SORT_BY_RISK";

// TEMPLATE ACTIONS
export const ADD_TO_TEMPLATE = "ADD_TO_TEMPLATE";
export const REMOVE_FROM_TEMPLATE = "REMOVE_FROM_TEMPLATE";
export const EDIT_TEMPLATE = "EDIT_TEMPLATE";
export const UPDATE_TEMPLATE_CONSEQUENCE = "UPDATE_TEMPLATE_CONSEQUENCE";
export const UPDATE_TEMPLATE_PROBABILITY = "UPDATE_TEMPLATE_PROBABILITY";
export const UPDATE_TEMPLATE_RISK = "UPDATE_TEMPLATE_RISK";
export const DELETE_TEMPLATE_RISK = "DELETE_TEMPLATE_RISK";
export const ADD_EMPTY_TEMPLATE_ROW = "ADD_EMPTY_TEMPLATE_ROW";
export const SORT_BY_TEMPLATE_RISK = "SORT_BY_TEMPLATE_RISK";

// STYLING ACTIONS
export const SET_BACKGROUND_COLOR = "SET_BACKGROUND_COLOR";
export const SET_RISK_COLOR = "SET_RISK_COLOR";

export const SET_HEADER_COLOR = "SET_HEADER_COLOR";
export const SET_RISK_COLOR1 = "SET_RISK_COLOR1";
export const SET_RISK_COLOR2 = "SET_RISK_COLOR2";

export const SET_HIGH_COLOR = "SET_HIGH_COLOR";
export const SET_MEDIUM_COLOR = "SET_MEDIUM_COLOR";
export const SET_LOW_COLOR = "SET_LOW_COLOR";
export const SET_TBC_COLOR = "SET_TBC_COLOR";
export const SET_OWNER_COLOR = "SET_OWNER_COLOR";
