
// RISK ACTIONS
export const UPDATE_CONSEQUENCE = 'UPDATE_CONSEQUENCE';
export const UPDATE_PROBABILITY = 'UPDATE_PROBABILITY';
export const DELETE_RISK = 'DELETE_RISK';

// STYLING ACTIONS
export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';

export const SET_MANAGERIAL_COLOR = 'SET_MANAGERIAL_COLOR';
export const SET_COMMERCIAL_COLOR = 'SET_COMMERCIAL_COLOR';
export const SET_TECHNICAL_COLOR = 'SET_TECHNICAL_COLOR';
export const SET_ENVIRONMENTAL_COLOR = 'SET_ENVIRONMENTAL_COLOR';
export const SET_LEGAL_COLOR = 'SET_LEGAL_COLOR';

export const SET_HEADER_COLOR = 'SET_HEADER_COLOR';
export const SET_RISK_COLOR1 = 'SET_RISK_COLOR1';
export const SET_RISK_COLOR2 = 'SET_RISK_COLOR2';

export const SET_HIGH_COLOR = 'SET_HIGH_COLOR';
export const SET_MEDIUM_COLOR = 'SET_MEDIUM_COLOR';
export const SET_LOW_COLOR = 'SET_LOW_COLOR';
export const SET_TBC_COLOR = 'SET_TBC_COLOR';
export const SET_OWNER_COLOR = 'SET_OWNER_COLOR';
